[package]
name = "decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
binread = "2.2.0"
thiserror = "1.0.30"
base64 = "0.13.0"
novafc-data-format = { path = "../novafc-software/data-format/" }
serde_json = "1.0"
